# Stage 1: Build the Go application
FROM golang:1.22-bookworm AS builder

WORKDIR /app

# Copy go.mod and go.sum files and download dependencies to leverage Docker cache
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the source code
COPY . .

# Build the executable binary
# CGO_ENABLED=0 ensures a statically linked binary
RUN CGO_ENABLED=0 go build -o server .

# Stage 2: Create a minimal runtime image
# Use a very minimal base image like 'scratch' or 'distroless' for security and size
FROM scratch

WORKDIR /app

# Copy the built binary from the 'builder' stage
COPY --from=builder /app/unit-converter-server .

# Expose the port your Go server listens on
EXPOSE 9090

# Command to run the executable when the container starts
CMD ["./unit-converter-server"]
